repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: bash -lc 'docker run --rm -v "$PWD:/work" -w /work koalaman/shellcheck:stable shellcheck -x -S style entrypoint.sh'
        language: system
        pass_filenames: false
      - id: hadolint
        name: hadolint
        entry: bash -lc 'docker run --rm -v "$PWD:/work" -w /work hadolint/hadolint:latest-debian hadolint Dockerfile'
        language: system
        pass_filenames: false
      - id: actionlint
        name: actionlint
        entry: bash -lc 'docker run --rm -v "$PWD:/work" -w /work ghcr.io/rhysd/actionlint:latest -color'
        language: system
        pass_filenames: false
      - id: yamllint
        name: yamllint
        entry: bash -lc 'docker run --rm -v "$PWD:/work" -w /work cytopia/yamllint -c .yamllint.yml .'
        language: system
        pass_filenames: false

