name: GitHub Action template
author: Krzysztof Szyper / ChristophShyper / biotyk@mail.com
description: Template repository for GitHub Actions
inputs:
  foobar:
    description: Some input variable
    required: false
    default: foobar
outputs:
  barfoo:
    description: Output from action
runs:
  using: docker
  image: docker://devopsinfra/template-action:latest
branding:
  color: purple
  icon: upload-cloud
