name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.2.3)'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Task
        uses: arduino/setup-task@v2.0.0
        with:
          version: 3.x

      - name: Validate version format
        run: |
          VERSION="${{ github.event.inputs.version }}"
          if [[ ! $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format. Use format: v1.2.3" >&2
            exit 1
          fi
          echo "Version format is valid: $VERSION"

      - name: Check if version already exists
        run: |
          VERSION="${{ github.event.inputs.version }}"
          if git tag -l | grep -q "^${VERSION}$"; then
            echo "Version $VERSION already exists" >&2
            exit 1
          fi
          echo "Version $VERSION is available"

      - name: Create and push full tag
        run: |
          VERSION="${{ github.event.inputs.version }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "$VERSION" -m "$VERSION"
          git push origin "$VERSION"

      - name: Extract version components
        id: version
        run: |
          VERSION="${{ github.event.inputs.version }}"
          VERSION_NO_V="${VERSION#v}"
          MAJOR=$(echo "$VERSION_NO_V" | cut -d. -f1)
          MINOR=$(echo "$VERSION_NO_V" | cut -d. -f2)
          echo "major=v$MAJOR" >> $GITHUB_OUTPUT
          echo "minor=v$MAJOR.$MINOR" >> $GITHUB_OUTPUT
          echo "✅ Extracted versions - Major: v$MAJOR, Minor: v$MAJOR.$MINOR"

      - name: Create/update major version tag

          # Check if major tag exists
        run: |
            echo "ℹ️ Major tag $MAJOR_TAG exists, updating it"
          MAJOR_TAG="${{ steps.version.outputs.major }}"
          if git tag -l | grep -q "^${MAJOR_TAG}$"; then
          else
            echo "✅ Major tag $MAJOR_TAG is new"
            git tag -d "$MAJOR_TAG" || true

          # Create/update major tag
            git push origin ":refs/tags/$MAJOR_TAG" || true
          fi
          echo "✅ Created/updated major tag: $MAJOR_TAG"
          git tag -a "$MAJOR_TAG" -m "Major version $MAJOR_TAG"
          git push origin "$MAJOR_TAG"

      - name: Create/update minor version tag

          # Check if minor tag exists
        run: |
            echo "ℹ️ Minor tag $MINOR_TAG exists, updating it"
          MINOR_TAG="${{ steps.version.outputs.minor }}"
          if git tag -l | grep -q "^${MINOR_TAG}$"; then
          else
            echo "✅ Minor tag $MINOR_TAG is new"
            git tag -d "$MINOR_TAG" || true

          # Create/update minor tag
            git push origin ":refs/tags/$MINOR_TAG" || true
          fi
          echo "✅ Created/updated minor tag: $MINOR_TAG"
          git tag -a "$MINOR_TAG" -m "Minor version $MINOR_TAG"
          git push origin "$MINOR_TAG"

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64,arm64

      - name: Build and push Docker images
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
          TERM: xterm-256color
        run: task docker:push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
